project:
  type: website
  output-dir: docs

editor:
  markdown:
    wrap: sentence

execute:
  freeze: auto

website:
  title: "Bayesian Regression: Theory & Practice"
  repo-url: https://github.com/quarto-dev/quarto-demo
  repo-actions: [edit, issue]
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Overview
      - section: "01: Basics"
        contents:
          - href: 01-basics.qmd
            text: Overview
          - href: practice-sheets/01a-wrangling-plotting.qmd
            text: Wrangling & plotting
          - href: practice-sheets/01b-simple-regression.qmd
            text: Simple linear regression
          - href: practice-sheets/01c-priors.qmd
            text: Priors
          - href: practice-sheets/01d-predictives.qmd
            text: Predictions
          - href: practice-sheets/01e-contrast-coding-tutorial.qmd
            text: Contrast coding (tutorial)
          - href: practice-sheets/01f-catPreds-exercises.qmd
            text: Categorical predictors (hands-on)
          - href: practice-sheets/01g-cheat-sheet.qmd
            text: Cheat sheet
      - section: "02: MCMC sampling"
        contents:
          - href: 02-MCMC.qmd
            text: Overview
          - href: practice-sheets/02a-MCMC-diagnostics.qmd
            text: MCMC diagnostics (tutorial)
      - section: "03: GLMs & beyond"
        contents:
          - href: practice-sheets/03a-GLM-tutorial.qmd
            text: GLM (tutorial)
          - href: practice-sheets/03b-GLM-exercises.qmd
            text: GLM (exercises)
          - href: practice-sheets/03c-distributional-models.qmd
            text: distributional models
          - href: practice-sheets/03d-mixture-models.qmd
            text: mixture models
      - section: "04: Model comparison"
        contents:
          - href: 04-model-comparison.qmd
            text: Overview
          - href: practice-sheets/04a-model-comparison.qmd
            text: Model comparison (practice)
      - section: "05: Multi-level models"
        contents:
          - href: 05-hierarchical-models.qmd
            text: Overview
          - href: practice-sheets/05a-hierarchical-models-tutorial.qmd
            text: Hierarchical models (tutorial)
          - href: practice-sheets/05b-hierarchical-models-exercises.qmd
            text: Hierarchical models (exercises)
          - href: practice-sheets/05c-multi-membership.qmd
            text: multi membership
          - href: practice-sheets/05d-MLM-pooling.qmd
            text: MLM-pooling
      - section: "06: Causal inference"
        contents:
          - href: practice-sheets/06-causal-inference.qmd
            text: Causal inference (practice)
      - section: "07: Non-linear models"
        contents:
          - href: practice-sheets/07a-nonLinear.qmd
            text: Custom non-linearity
          - href: practice-sheets/07b-GAMs.qmd
            text: GAMs

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: show
    code-summary: "Toggle code"
